"""init: create order/order_item tables

Revision ID: 2dc80ba9cbe1
Revises: 42ddb59b501a
Create Date: 2025-12-12 13:40:06.263607

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2dc80ba9cbe1'
down_revision = '42ddb59b501a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'owner_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_comment='下单人ID，对应user.id',
               existing_nullable=False,
               postgresql_using='owner_id::uuid') # 显式指定转换规则
    op.alter_column('orderitem', 'order_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Uuid(),
               existing_comment='订单号，对应order.id',
               existing_nullable=False,
               postgresql_using='order_id::uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderitem', 'order_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=100),
               existing_comment='订单号，对应order.id',
               existing_nullable=False)
    op.alter_column('order', 'owner_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_comment='下单人ID，对应user.id',
               existing_nullable=False)
    # ### end Alembic commands ###
