"""init: create order/order_item tables

Revision ID: 42ddb59b501a
Revises: 3790307697eb
Create Date: 2025-12-11 16:00:20.167936

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42ddb59b501a'
down_revision = '3790307697eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'id',
               existing_type=sa.UUID(),
               comment='主键',
               existing_nullable=False)
    op.alter_column('order', 'order_no',
               existing_type=sa.VARCHAR(),
               comment='订单号',
               existing_nullable=False)
    op.alter_column('order', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总金额',
               existing_nullable=False)
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='下单时间',
               existing_nullable=False)
    op.alter_column('order', 'owner_id',
               existing_type=sa.VARCHAR(),
               comment='下单人ID，对应user.id',
               existing_nullable=False)
    op.alter_column('orderitem', 'id',
               existing_type=sa.UUID(),
               comment='主键',
               existing_nullable=False)
    op.alter_column('orderitem', 'order_id',
               existing_type=sa.VARCHAR(length=100),
               comment='订单号，对应order.id',
               existing_nullable=False)
    op.alter_column('orderitem', 'product_no',
               existing_type=sa.VARCHAR(length=100),
               comment='商品编号',
               existing_nullable=False)
    op.alter_column('orderitem', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='商品名称',
               existing_nullable=True)
    op.alter_column('orderitem', 'count',
               existing_type=sa.INTEGER(),
               comment='购买数量',
               existing_nullable=False)
    op.alter_column('orderitem', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='商品单价',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderitem', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='商品单价',
               existing_nullable=False)
    op.alter_column('orderitem', 'count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='购买数量',
               existing_nullable=False)
    op.alter_column('orderitem', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=True)
    op.alter_column('orderitem', 'product_no',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='商品编号',
               existing_nullable=False)
    op.alter_column('orderitem', 'order_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='订单号，对应order.id',
               existing_nullable=False)
    op.alter_column('orderitem', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False)
    op.alter_column('order', 'owner_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='下单人ID，对应user.id',
               existing_nullable=False)
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='下单时间',
               existing_nullable=False)
    op.alter_column('order', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总金额',
               existing_nullable=False)
    op.alter_column('order', 'order_no',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='订单号',
               existing_nullable=False)
    op.alter_column('order', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False)
    # ### end Alembic commands ###
