"""add foreign key in table OrderItem

Revision ID: 57b86bbaf4d8
Revises: 2dc80ba9cbe1
Create Date: 2025-12-12 14:14:54.443792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57b86bbaf4d8'
down_revision = '2dc80ba9cbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    # ### end Alembic commands ###
